name: Fetch Google Sheet CSV

on:
  schedule:
    - cron: '0 1 * * *' 
  workflow_dispatch: 
jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Ensure curl is installed
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Fetch CSV data from Google Sheet
        run: |
          curl -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vQVennPeX922c0SdERLUY5Wgeq5pPAUdHVj680pplP2CFgdgdki8e2igY7VjsQOVRjZGCCdHZT5AbuE/pub?gid=258279914&single=true&output=csv" -o dataset.csv

     
      - name: Commit file
        run: |
          
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          git add dataset.csv
                    
          git commit -m "Automated data update from Google Sheet [skip ci]" || echo "No changes to commit"
          
          git push
